version: "3"
networks:
  local:
  traefik:
    external: true
services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
    networks:
      - local
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - DEMO=True
      - MARABUNTA_MODE=demo
      - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons,/odoo/src/addons,/odoo/external-src/server-tools
    hostname: ${ENV}-${COMPOSE_PROJECT_NAME}
    labels:
      docky.access.help: http://${COMPOSE_PROJECT_NAME}.dy
      docky.main.service: true
      docky.user: odoo
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.www.frontend.rule: Host:${COMPOSE_PROJECT_NAME}.dy
      traefik.longpolling.frontend.rule: Host:${COMPOSE_PROJECT_NAME}.dy;PathPrefix:/longpolling/
    links:
      - db
    networks:
      - local
      - traefik
volumes:
  py3o_tmp: null
