networks:
  default:
    external:
      name: dy
services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo
      - VIRTUAL_HOST=odoo.dy
      - VIRTUAL_PORT=8069
    links:
      - db
    ports: 
      - 8069:8069
    networks:
      default:
        aliases:
          - odoo.dy
    volumes:
      - ./odoo:/odoo
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
version: '3'
volumes:
  py3o_tmp: null
