version: "3.7"
networks:
  local:
  traefik:
    external: true
services:
  db:
    environment:
      - PGUSER=$PGUSER
      - PGDATABASE=$PGDATABASE
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
    networks:
      - local
  odoo:
    build: odoo
    environment:
      - DEMO=True
      - MARABUNTA_MODE=demo
      # you can specify your own addons path, if you don't want to use links
      # - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons,/odoo/src/addons,/odoo/external-src/server-tools
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.rule=Host(`${COMPOSE_PROJECT_NAME}.localhost`) && PathPrefix(`/longpolling/`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=odoo"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-long.service=odoo_long"
      - "traefik.http.services.odoo.loadbalancer.server.port=8069"
      - "traefik.http.services.odoo_long.loadbalancer.server.port=8072"
      - "docky.access.help=${COMPOSE_PROJECT_NAME}.localhost"
    links:
      - db
    networks:
      - local
      - traefik
