version: "3.7"
networks:
  local:
  traefik:
    external: true
services:
  db:
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_DB=$PGDATABASE
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
    networks:
      - local
  odoo:
    build: odoo
    environment:
      - DEMO=True
      - MARABUNTA_MODE=demo
      - ADDONS_PATH=/odoo/links,/odoo/local-src,/odoo/src/odoo/addons,/odoo/src/addons,/odoo/external-src/server-tools
    labels:
      docky.access.help: http://${COMPOSE_PROJECT_NAME}.dy
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.www.frontend.rule: Host:${COMPOSE_PROJECT_NAME}.dy
      traefik.longpolling.frontend.rule: Host:${COMPOSE_PROJECT_NAME}.dy;PathPrefix:/longpolling/
    links:
      - db
    networks:
      - local
      - traefik
