services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/:/var/lib/postgresql/data
  odoo:
    build: odoo
    environment:
      - PYTHONDONTWRITEBYTECODE=True
      - LOCAL_USER_ID=$UID
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=db
      - RUNNING_ENV=$ENV
      - MARABUNTA_MODE=demo
      - MARABUNTA_MIGRATION_FILE=/odoo/migration/migration.yml
    hostname: ${ENV}-${COMPOSE_PROJECT_NAME}
    labels:
      docky.access.help: http://${COMPOSE_PROJECT_NAME}.dy
      docky.main.service: true
      docky.user: odoo
      traefik.enable: true
      traefik.www.frontend.rule: Host:${COMPOSE_PROJECT_NAME}.dy
      traefik.longpolling.frontend.rule: Host:${COMPOSE_PROJECT_NAME}.dy;PathPrefix:/longpolling/
    links:
      - db
    volumes:
      - ./odoo/local-src:/odoo/local-src
      - ./odoo/external-src:/odoo/external-src
      - ./odoo/links:/odoo/links
      - ./odoo/songs:/odoo/songs
      - ./odoo/migration:/odoo/migration
      - ./data/addons:/data/odoo/addons
      - ./data/filestore:/data/odoo/filestore
      - ./data/sessions:/data/odoo/sessions
version: '3'
volumes:
  py3o_tmp: null
