services:
  odoo:
    build: odoo # at term, CI should build it for us
    environment:
      - MARABUNTA_MODE=demo
    labels:
        traefik.enable: true
        traefik.www.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.dev.akretion.com
        traefik.longpolling.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.dev.akretion.com;PathPrefix:/longpolling/
        docky.access.help: https://${COMPOSE_PROJECT_NAME}.dev.akretion.com
version: '3.7'

